modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    modId="charm"
    version="${version}"
    displayName="Charm"
    credits=""
    authors="svenhjol"
    description='''
Tweaks and additions to Minecraft without changing core gameplay.
    '''
    logoFile="icon.png"

[[dependencies.charm]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.charm]]
    modId="charmony"
    mandatory=true
    versionRange="[${charmony_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.charm]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"
