modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    modId="charm"
    version="${version}"
    displayName="Charm (client)"
    credits=""
    authors="svenhjol"
    description='''
Client-only tweaks for Minecraft. Works on vanilla servers!
    '''
    logoFile="icon.png"

[[dependencies.charm]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.charm]]
    modId="charm_core"
    mandatory=true
    versionRange="[${core_version},)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.charm]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="CLIENT"
