modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
[[mods]]
modId="charm"
version="${version}"
displayName="Charm"
credits=""
authors="svenhjol"
description='''
Tweaks and additions to Minecraft without changing core gameplay.
'''
logoFile="icon.png"
[[dependencies.charm]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.charm]]
    modId="charm_api"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.charm]]
    modId="charm_core"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.charm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
